### ISSUE TITLE
Outputting each path record to a new file

### ISSUE THREAD

**Issue by nitrocode** [miku/xmlcutty#2]
I noticed when I cut the xml for [this xml](https://raw.githubusercontent.com/xAranaktu/FIFA-18---Career-Mode-Cheat-Table/master/FIFA18%20-%20Career%20Table.CT), I can get back all of my `CheatEntry`'s but I'd like to output each record into a separate file denoted by its ID.

For instance here is my starting point

    xmlcutty -path "/CheatTable/CheatEntries/CheatEntry" FIFA.CT

I'd like it to read this cheat entry and the others

    <CheatEntry>
      <ID>1621</ID>
      <Description>...</Description>
      <LastState Value="" RealAddress="..."/>
      <GroupHeader>...</GroupHeader>
    </CheatEntry>

And save `1621.xml` to a directory `xmlcutty-output/`

Is there a way to do this currently with xmlcutty somehow with bash pipes or can this be a feature request?

    xmlcutty -path "/CheatTable/CheatEntries/CheatEntry" \
                    -output-dir xmlcutty-output \
                    -record-as-file "/CheatTable/CheatEntries/CheatEntry/ID" \
                    FIFA.CT

**Comment by miku** [comment]
> Is there a way to do this currently with xmlcutty somehow 

Unfortunately, no.

> can this be a feature request

It sure can, but it would be currently relatively low on the todo-list.

**Comment by miku** [comment]
Closing this, as this is partially addressed in #3.
