### ISSUE TITLE
Parse each record into unformatted xml

### ISSUE THREAD

**Issue by nitrocode** [miku/xmlcutty#3]
It would be nice to remove the formatting for each record so you can iterate over each record

    xmlcutty -path /CheatTable/CheatEntries/CheatEntry FIFA.CT | \
      while read record; do echo $record; done;

At the moment the above returns all the records in a pretty format making it difficult to parse individual records.

    xmlcutty -unformatted -path /CheatTable/CheatEntries/CheatEntry FIFA.CT | \
      while read record; do echo $record; done;

**Comment by miku** [comment]
Ok, this might be easier than #2. I just added a way to specify multiple newlines (or any character) in `-rename` which might help to distinguish records. It's wrapped up in [0.1.5](https://github.com/miku/xmlcutty/releases/tag/v0.1.5), hope it's somehow useful.
